name: logbook_api_project
services:
  logbookdb:
    container_name: logbook_api_db
    image: mcr.microsoft.com/mssql/server:latest
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    networks:
        - logbook_backend   
    volumes:
        - mssql_data:/var/opt/mssql
    ports:
        - 8001:1433
    
  logbookapi:
    container_name: logbook-api
    image: promisea/logbookapi:v1.0
    pull_policy: always
    build:
      context: .
      dockerfile: LogBook API/Dockerfile
    networks:
        - logbook_backend
    environment:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
        - JwtSettings__validIssuer=${JWT_VALID_ISSUER}
        - JwtSettings__validAudience=${JWT_VALID_AUDIENCE}
        - JwtSettings__secretKey=${JWT_SECRET_KEY}
        - JwtSettings__expires=${JWT_EXPIRES}
        - EmailConfiguration__UserName=${EMAIL_USERNAME}
        - EmailConfiguration__SmtpServer=${EMAIL_SMTP_SERVER}
        - EmailConfiguration__Port=${EMAIL_PORT}
        - EmailConfiguration__Password=${EMAIL_PASSWORD}
        - EmailConfiguration__From=${EMAIL_FROM}
    ports:
        - 8002:8080
        - 8003:8081
    restart: on-failure
    depends_on:
        - logbookdb
        
networks:
  logbook_backend:
volumes: 
  mssql_data:
    